heat_template_version: 2016-10-14

description: >
  Heat Template to create a VM with 4 network interfaces

parameters:
  image:
    type: string
    description: Image to use for the VM
    default: ubuntu-20.04
  flavor:
    type: string
    description: Flavor to use for the VM
    default: m1.medium
  key_name:
    type: string
    description: Name of an existing key pair
  network_1:
    type: string
    description: First network for the VM's NIC
  network_2:
    type: string
    description: Second network for the VM's NIC
  network_3:
    type: string
    description: Third network for the VM's NIC
  network_4:
    type: string
    description: Fourth network for the VM's NIC

resources:
  # Create a Security Group
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: vm_security_group
      rules:
        - protocol: icmp
          direction: ingress
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          direction: ingress

  # Create the VM with 4 network interfaces
  my_vm:
    type: OS::Nova::Server
    properties:
      name: my-new-vm
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      security_groups: [ { get_resource: security_group } ]
      networks:
        - network: { get_param: network_1 }
        - network: { get_param: network_2 }
        - network: { get_param: network_3 }
        - network: { get_param: network_4 }

outputs:
  instance_name:
    description: Name of the created instance
    value: { get_attr: [ my_vm, name ] }
  instance_ip:
    description: The IP addresses assigned to the instance
    value: { get_attr: [ my_vm, networks ] }



openstack stack create -t vm_with_4_interfaces.yaml \
--parameter image=ubuntu-20.04 \
--parameter flavor=m1.medium \
--parameter key_name=mykey \
--parameter network_1=a1b2c3d4-e5f6-7890-gh12-ijklmno3p4 \
--parameter network_2=b1c2d3e4-f5g6-7890-hi12-jklmnpo5q6 \
--parameter network_3=c1d2e3f4-g5h6-7890-ij12-klmnoq6r7s \
--parameter network_4=d1e2f3g4-h5i6-7890-jk12-lmnopq7r8t \
my-heat-stack

openstack stack show my-heat-stack
